### ISSUE TITLE
[FEATURE REQUEST] Grid view with thumbnail

### ISSUE THREAD

**Issue by mbahArip** [menukaonline/goindex-extended#50]
I'm wondering if it's possible to add grid view with thumbnail preview for images / videos something like this?
![image_2021-12-17_144222](https://user-images.githubusercontent.com/62494292/146507936-b8c07f2f-fd4d-4ae9-87be-c271720e94d5.png)

So i'm currently using goindex acrou, and i found yours with in my opinion have better ui layout than acrou.
I kinda want to switch but i have this folder full of photos and vids.

**Comment by cheems** [comment]
Yeah, I already did some experiments regarding the feature you mentioned. But it was not enough for the implementation. I will work on it after completing the tasks on the to-do list.
